// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGMISXDNqaIaYmQzzCurdlRmj4k8rLcaM',
    appId: '1:610193133250:web:3a35cf190a6309160c355b',
    messagingSenderId: '610193133250',
    projectId: 'myshop-au',
    authDomain: 'myshop-au.firebaseapp.com',
    storageBucket: 'myshop-au.appspot.com',
    measurementId: 'G-MZBWKW1XEJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXpzlhlGGBb93Xwt9vLsd3xdTN8K8--dA',
    appId: '1:610193133250:android:17cc189108756be70c355b',
    messagingSenderId: '610193133250',
    projectId: 'myshop-au',
    storageBucket: 'myshop-au.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnk2Pnbg8hYbP9zNw1IuT2oKMmUOAaplw',
    appId: '1:610193133250:ios:190e8b4008dbf3b60c355b',
    messagingSenderId: '610193133250',
    projectId: 'myshop-au',
    storageBucket: 'myshop-au.appspot.com',
    iosClientId: '610193133250-nmhhoa5ep8d4c9n4064kbej3kphq3pgv.apps.googleusercontent.com',
    iosBundleId: 'com.myshopau',
  );
}
